### ISSUE TITLE
Increase stability under high load

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-explorer#14]
OKR: Q2 2023

Currently block explorers are stucking and failing under high load. We need to increase blockexplorer uptime to 98%

TODO: @DmytroNazarenko add more info
```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/blockscout/issues/40
```

**Comment by imostovenko** [comment]
Options to try are described here: https://www.notion.so/skalelabs/Explorer-1-1-0-3a5ec426f7e8484aae2cd9fa78c355e1?pvs=4#6d9cd2767360427f836a7aa9c2e261e0
