### ISSUE TITLE
Not optimized recourse usage on skale-explorer for 8 skale chains without any load

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skale-explorer#23]
**Describe the bug**
Skale-explorer works with low downtime (>98% of uptime) but uses too many resources of the instance. Chains are without any load, so under load blockscout are going to crash or stuck with the lack of resources. 

**Preconditions**
Active 8 chains without load 
Active Skale-Proxy as the endpoint

**To Reproduce**
1. Connect to the instance where the skale-explorer is.
2. Check resource usage in any convenient tool

**Expected behavior**
Total RSS and CPU usage should use 50% of total resources   (400% of 800% CPU and 16GB of 32GB RSS )

**Actual state:**
Skale-explorer usues almost 100% of allocated resources 

![image](https://github.com/skalenetwork/skale-explorer/assets/84327300/c1b3c11b-7aa8-4fd3-9292-104a5f7bc85e)

**Comment by PolinaKiporenko** [comment]
should be recheck on 1.1.0 version
