### ISSUE TITLE
Network can't be added to metamask

### ISSUE THREAD

**Issue by DimaStebaev** [skalenetwork/skale-explorer#25]
**Description**
At the bottom of a explorer page a button `Add {network}` does not work.
![изображение](https://github.com/skalenetwork/skale-explorer/assets/1651343/be759756-81ae-4a40-9a13-2c2d6ec8ffaf)

**To Reproduce**
1. Open explorer (for example https://staging-perfect-parallel-gacrux.explorer.staging-v3.skalenodes.com)
2. Scroll down
3. Press `Add staging-perfect-parallel-gacrux`
4. Shed a tear

**Expected behavior**
The network is added to metamast

**Desktop:**
 - OS: Ubuntu 23.04
 - Browser: Firefox 
 - Version: 118.0.2

**Smartphone:**
 - Device: Google Pixel 6 Pro
 - OS: Android 14 (UP1A.231005.007)
 - Browser: Chrome
 - Version: 119.0.6045.66

**Comment by PolinaKiporenko** [comment]
Recheck after migration to new UI
