### ISSUE TITLE
Deployed contract from contract factory is presented as EOA

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/skale-explorer#26]
If you deploy a contract from a contract factory it shows as EOA
![image](https://user-images.githubusercontent.com/12778980/214708568-70088990-ed6d-42ee-979d-81de25a3c4b8.png)

![image](https://user-images.githubusercontent.com/12778980/214708682-e7bff378-3dbd-4b39-b9eb-0b0d369c7dac.png)

Similar issue to:
- skalenetwork/blockscout#9

**Comment by PolinaKiporenko** [comment]
Try to reproduce on new version 1.1.0

**Comment by PolinaKiporenko** [comment]
should be fixed by enabling tracing (internal tx)

**Comment by OleksanderSalamatov** [comment]
Verified

blockscout: `2.1.0-beta.2`

schain: mad-rusty-vindemiatrix
Factory was deployed with Remix and SimpleStorage contract was deployed via Factory
Contracts do not show as EOA both when not verified and verified

SimpleStorage contract: `0x59f732c6Bf743086DB2a7DbB627AeC3da14bce3B`
![image](https://github.com/user-attachments/assets/d521cb7c-68da-4b00-bbc0-86cf63e78adb)

StorageFactory contract: `0xF318Cc0E0ebFA47d23CAc621415BA05808056b33`
![image](https://github.com/user-attachments/assets/3e9502e2-b3ff-40b2-b97e-ea429cc98c39)
