### ISSUE TITLE
Coinbase wallet is connected instead of Metamask

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/skale-explorer#27]
**Describe the bug**
If there are two wallets are active in the browser - Coinbase and Metamask - while choosing Metamask wallet to connect, Coinbase popup window is displayed. 

**To Reproduce**
1. Go to to any contract and choose "Write contract"
2. Click on "Connect wallet" and choose Metamask
3. See Coinbase popup window

**Expected behavior**
Metamask popup window is displayed with offer to connect wallet

**Screenshots**

https://github.com/skalenetwork/skale-explorer/assets/105824131/915ed2dd-e94a-42aa-b664-773ce1e25456

**Comment by DmytroNazarenko** [comment]
blockscout v2.0.0
testnet: https://aware-fake-trim-testnet.explorer.testnet.skalenodes.com/

**Comment by yatsunastya** [comment]
Checked on testnet :white_check_mark: 

https://github.com/skalenetwork/skale-explorer/assets/105824131/ab9e67e5-d1ea-42cb-93fe-32f6272ac983
