### ISSUE TITLE
Enable tracing in Blockexplorer 

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/skale-explorer#29]
Need to enable internal transactions in Blockscout and fetch info from trace log by using archive node with tracing 

 - https://base.blockscout.com/tx/0xc4564ca8b58fdd060674cf2421072a865d03e692413f646fbd4e6d4eaa051d4b?tab=internal
 - https://base.blockscout.com/tx/0xc4564ca8b58fdd060674cf2421072a865d03e692413f646fbd4e6d4eaa051d4b?tab=raw_trace

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: `2.1.0-beta.2`

:heavy_check_mark:  Internal [transactions](https://prickly-wary-sirius.legacy-explorer.skalenodes.com/tx/0x5aa245709543f3ffb3abe4f6e67b9b1bd99cba409b283059794deaeb59a98d7a?tab=internal) are enabled.
:heavy_check_mark:  Transaction info is fetched from [trace log](https://prickly-wary-sirius.legacy-explorer.skalenodes.com/tx/0x5aa245709543f3ffb3abe4f6e67b9b1bd99cba409b283059794deaeb59a98d7a?tab=raw_trace)
