### ISSUE TITLE
Fix erc721 names

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-explorer#43]
Currently on tokens page erc721 tokens names are not available

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: `2.1.0-beta.2`

Before :arrow_down: 
![Image](https://github.com/user-attachments/assets/44e3053b-6ef2-4c3f-b52a-881ac0bd0cfa)

After :arrow_down: 
![Image](https://github.com/user-attachments/assets/7d6e8bdc-7365-49ab-b6bd-0e80e54e18f7)
