### ISSUE TITLE
Deal with PoW transactions (gasPrices make the stats unreadable)

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-explorer#44]
We need to handle POW transactions on the UI to improve visibility

<img width="1479" alt="image" src="https://github.com/skalenetwork/skale-explorer/assets/17967562/2e570865-906b-4ee8-900f-4048126e088a">

**Comment by OleksanderSalamatov** [comment]
Verified

blockscout: `2.1.0-beta.2`
PoW transactions gas fee showed in Xe+Y format
![image](https://github.com/user-attachments/assets/4ec56ac2-c6f3-4358-b2d2-e96c556f486b)
